#!/usr/bin/env bash


DARK_MODE_TOGGLE="<script type=\"text\/javascript\" src=\"\$relpath^doxygen-awesome-darkmode-toggle.js\"><\/script>\n <script type=\"text\/javascript\">\n DoxygenAwesomeDarkModeToggle.init()\n <\/script>"

FRAGMENT_COPY_BUTTON="<script type=\"text\/javascript\" src=\"\$relpath^doxygen-awesome-fragment-copy-button.js\"><\/script>\n <script type=\"text\/javascript\">\n DoxygenAwesomeFragmentCopyButton.init()\n <\/script>"

INTERACTIVE_TOC="<script type=\"text\/javascript\" src=\"\$relpath^doxygen-awesome-interactive-toc.js\"><\/script>\n <script type=\"text\/javascript\">\n DoxygenAwesomeInteractiveToc.init()\n <\/script>"

PARAGRAPH_LINK="<script type=\"text\/javascript\" src=\"\$relpath^doxygen-awesome-paragraph-link.js\"><\/script>\n <script type=\"text\/javascript\">\n DoxygenAwesomeParagraphLink.init()\n <\/script>"

# Generate the HTML files with Doxygen
doxygen -w html header.html delete_me.html delete_me.css || {
    echo "Error: Doxygen command failed."
    exit 1
}

# Replace text in the header of the HTML files generated by Doxygen (the first argument)
sed -i "/<\/head>/i ${DARK_MODE_TOGGLE}\n\n${FRAGMENT_COPY_BUTTON}\n\n${INTERACTIVE_TOC}\n\n${PARAGRAPH_LINK}\n" "${PWD}/header.html"
